name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: run commands
      run: |
        whoami
        echo "aooooooooooooo"
        ls -a ~/.ssh/
        echo "Host lorencini.tech
        HostKeyAlgorithms +ssh-rsa
        PubkeyAcceptedKeyTypes +ssh-rsa" > ~/.ssh/config
        ssh-keyscan -t rsa lorencini.tech >> ~/.ssh/known_hosts
        echo ${{ secrets.SSH_NC_KEY }} > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git remote add my_server ${{ secrets.SERVER }}
        git push -u origin master
        